Initial commit of React Native app
    - this command was executed
    npx @react-native-community/cli init PC_APP_CASH_V_1_0_0
    - this is the output

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######

              Welcome to React Native 0.78.2!
                 Learn once, write anywhere

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing dependencies
✔ Do you want to install CocoaPods now? Needed for running iOS project … yes
✔ Installing Ruby Gems
ℹ Installing Ruby Gems
✖ Installing CocoaPods
error
error Installing Cocoapods failed. This doesn't affect project initialization and you can safely proceed. However, you will need to install Cocoapods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
CocoaPods documentation: https://cocoapods.org/

info 💡 To enable automatic CocoaPods installation when building for iOS you can create react-native.config.js with automaticPodsInstallation field.
For more details, see https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectiosautomaticpodsinstallation

✔ Initializing Git repository

  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/debajyotigoswami/Desktop/Projects/OFFICE_PROJECT/Desktop_PC_Cash_Collection/PC_APP_CASH_V_1_0_0" && npx react-native run-android

  Run instructions for iOS:
    • cd "/Users/debajyotigoswami/Desktop/Projects/OFFICE_PROJECT/Desktop_PC_Cash_Collection/PC_APP_CASH_V_1_0_0"

    • npx react-native run-ios
    - or -
    • Open PC_APP_CASH_V_1_0_0/ios/PC_APP_CASH_V_1_0_0.xcodeproj in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.

    - nested git deleted
    by rm -rf PC_APP_CASH_V_1_0_0/.git
    - then git add . executed